### ISSUE TITLE
Improve Normalize CSS

### ISSUE THREAD

**Issue by devenini** [locomotivemtl/locomotive-boilerplate#180]
Fix current issue of `_normalize.scss` overriding styling of different tags e.g.
```scss
// Remove list styles on ul, ol elements with a class, which suggests default styling will be removed
ul[class],
ol[class] {
    margin: 0;
    padding: 0;
    list-style: none;
}
```
...
```scss
// Remove a elements default styles if they have a class
a[class] {
    color: inherit;
    text-decoration: none;
}
```
