### ISSUE TITLE
A better clearfix

### ISSUE THREAD

**Issue by mcaskill** [locomotivemtl/locomotive-boilerplate#23]
I've noticed two things about the clearfix used in the Boilerplate:

1. It's an old syntax.
2. There's no mixin.

Add this to `tools/mixins`:

```scss
// Micro clearfix, as per {@link css-101.org/articles/clearfix/latest-new-clearfix-so-far.php CSS Mojo}
//
// @see inuitcss/generic.clearfix

@mixin u-clearfix {
	&:after {
		content : "";
		display : table;
		clear   : both;
	}
}
```

Replace existing solution in `trumps/helpers` with this:

```scss
/**
 * Contain Floats
 */

%u-clearfix {
	@include u-clearfix;
}

	.u-clearfix {
		@extend %u-clearfix;
	}
```
